---
## in cases where python is installed in the system, use core ansible modules

## /etc/environment
- name: "Setting http_proxy variable to /etc/environment "
  lineinfile:
    dest=/etc/environment
    line="{{ item }}={{ http_proxy_address }}"
    regexp="^{{ item }}="
  when: not (http_proxy_address is undefined or http_proxy_address is none or http_proxy_address | trim == '') and etc_environment
  with_items:
    - http_proxy
    - HTTP_PROXY

- name: Setting https_proxy variable to /etc/environment
  lineinfile:
    dest=/etc/environment
    line="{{ item }}={{ https_proxy_address }}"
    regexp="^{{ item }}="
  when: not (https_proxy_address is undefined or https_proxy_address is none or https_proxy_address | trim == '') and etc_environment
  with_items:
    - https_proxy
    - HTTPS_PROXY

- name: Setting no_proxy variable to /etc/environment
  lineinfile:
    dest=/etc/environment
    line="{{ item }}={{ no_proxy_list }}"
    regexp="^{{ item }}="
  when: not (no_proxy_list is undefined or no_proxy_list is none or no_proxy_list | trim == '') and etc_environment
  with_items:
    - no_proxy
    - NO_PROXY

- name: Setting ftp_proxy variable to /etc/environment
  lineinfile:
    dest=/etc/environment
    line="{{ item }}={{ ftp_proxy_address }}"
    regexp="^{{ item }}="
  when: not (ftp_proxy_address is undefined or ftp_proxy_address is none or ftp_proxy_address | trim == '') and etc_environment
  with_items:
    - ftp_proxy
    - FTP_PROXY

## docker proxy
- name: Creating docker.service.d folder in /etc/systemd/system/docker.service.d
  file:
    path=/etc/systemd/system/docker.service.d
    state=directory
    owner=root
    group=root
    mode=0755
    recurse=yes
  when: docker_proxy
  notify: systemctl daemon-reload

- name: Creates http-proxy.conf if not present
  file:
    path=/etc/systemd/system/docker.service.d/http-proxy.conf
    state=touch
    owner=root
    group=root
    mode=0755
  when: docker_proxy
  changed_when: False
  notify: systemctl daemon-reload

- name: Adds [Service] header to systemd docker file
  lineinfile:
    dest=/etc/systemd/system/docker.service.d/http-proxy.conf
    line="[Service]"
  when: docker_proxy
  notify: systemctl daemon-reload

- name: Adds HTTP_PROXY environment to systemd docker file
  lineinfile:
    dest=/etc/systemd/system/docker.service.d/http-proxy.conf
    line='Environment="{{ item }}={{ http_proxy_address }}"'
    regexp="^Environment=\"{{ item }}="
  when: not (http_proxy_address is undefined or http_proxy_address is none or http_proxy_address | trim == '') and docker_proxy
  with_items:
    - http_proxy
    - HTTP_PROXY
  notify: systemctl daemon-reload

- name: Adds HTTPS_PROXY environment to systemd docker file
  lineinfile:
    dest=/etc/systemd/system/docker.service.d/http-proxy.conf
    line='Environment="{{ item }}={{ https_proxy_address }}"'
    regexp="^Environment=\"{{ item }}="
  when: not (https_proxy_address is undefined or https_proxy_address is none or https_proxy_address | trim == '') and docker_proxy
  with_items:
    - https_proxy
    - HTTPS_PROXY
  notify: systemctl daemon-reload

- name: Adds FTP_PROXY environment to systemd docker file
  lineinfile:
    dest=/etc/systemd/system/docker.service.d/http-proxy.conf
    line='Environment="{{ item }}={{ ftp_proxy_address }}"'
    regexp="^Environment=\"{{ item }}="
  when: not (ftp_proxy_address is undefined or ftp_proxy_address is none or ftp_proxy_address | trim == '') and docker_proxy
  with_items:
    - ftp_proxy
    - FTP_PROXY
  notify: systemctl daemon-reload

- name: Adds NO_PROXY environment to systemd docker file
  lineinfile:
    dest=/etc/systemd/system/docker.service.d/http-proxy.conf
    line='Environment="{{ item }}={{ no_proxy_list }}"'
    regexp="^Environment=\"{{ item }}="
  when: not (no_proxy_list is undefined or no_proxy_list is none or no_proxy_list | trim == '') and docker_proxy
  with_items:
    - no_proxy
    - NO_PROXY
  notify: systemctl daemon-reload

- name: set http proxy to /etc/apt/apt.conf.d/02-apt-proxy
  lineinfile:
    dest=/etc/apt/apt.conf.d/02-apt-proxy
    line='Acquire::http::proxy "{{ apt_http_proxy_address }}";'
    regexp="^Acquire::http::proxy"
  when: not (apt_http_proxy_address is undefined or apt_http_proxy_address is none or apt_http_proxy_address | trim == '') and apt_http_proxy

- name: set https proxy to /etc/apt/apt.conf.d/02-apt-proxy
  lineinfile:
    dest=/etc/apt/apt.conf.d/02-apt-proxy
    line='Acquire::https::proxy "{{ apt_https_proxy_address }}";'
    regexp="^Acquire::https::proxy"
  when: not (apt_https_proxy_address is undefined or apt_https_proxy_address is none or apt_https_proxy_address | trim == '') and apt_https_proxy

- name: set ftp proxy to /etc/apt/apt.conf.d/02-apt-proxy
  lineinfile:
    dest=/etc/apt/apt.conf.d/02-apt-proxy
    line='Acquire::ftp::proxy "{{ apt_ftp_proxy_address }}";'
    regexp="^Acquire::ftp::proxy"
  when: not (apt_ftp_proxy_address is undefined or apt_ftp_proxy_address is none or apt_ftp_proxy_address | trim == '') and apt_ftp_proxy
