## in cases where python is NOT installed in the system, use raw ansible modules

## /etc/environment
- name: Touch /etc/environment
  raw: touch /etc/environment
  when: etc_environment

- name: Setting http_proxy variable to /etc/environment
  raw: grep -q "{{ item }}={{ http_proxy_address }}" "/etc/environment" ||  echo '{{ item }}={{ http_proxy_address }}' >> /etc/environment
  with_items:
    - http_proxy
    - HTTP_PROXY
  when: not (http_proxy_address is undefined or http_proxy_address is none or http_proxy_address | trim == '') and etc_environment

- name: Setting https_proxy variable to /etc/environment
  raw: grep -q "{{ item }}={{ https_proxy_address }}" "/etc/environment" || echo '{{ item }}={{ https_proxy_address }}' >> /etc/environment
  with_items:
    - https_proxy
    - HTTPS_PROXY
  when: not (https_proxy_address is undefined or https_proxy_address is none or https_proxy_address | trim == '') and etc_environment

- name: Setting no_proxy variable to /etc/environment
  raw: grep -q "{{ item }}={{ no_proxy_list }}" "/etc/environment" || echo '{{ item }}={{ no_proxy_list }}' >> /etc/environment
  with_items:
    - no_proxy
    - NO_PROXY
  when: not (no_proxy_list is undefined or no_proxy_list is none or no_proxy_list | trim == '') and etc_environment

- name: Setting ftp_proxy variable to /etc/environment
  raw: grep -q "{{ item }}={{ ftp_proxy_address }}" "/etc/environment" || echo '{{ item }}={{ ftp_proxy_address }}' >> /etc/environment
  with_items:
    - ftp_proxy
    - FTP_PROXY
  when: not (ftp_proxy_address is undefined or ftp_proxy_address is none or ftp_proxy_address | trim == '') and etc_environment

- name: Setting no_proxy variable to /etc/environment
  raw: grep -q "{{ item }}={{ no_proxy_list }}" "/etc/environment" || echo '{{ item }}={{ no_proxy_list }}' >> /etc/environment
  with_items:
    - no_proxy
    - NO_PROXY
  when: not (no_proxy_list is undefined or no_proxy_list is none or no_proxy_list | trim == '') and etc_environment


## docker proxy
- name: Creating docker.service.d folder in /etc/systemd/system/docker.service.d
  raw: mkdir -p /etc/systemd/system/docker.service.d
  when: docker_proxy

- name: Creates http-proxy.conf if not present
  raw: touch /etc/systemd/system/docker.service.d/http-proxy.conf
  when: docker_proxy

- name: Adds [Service] header to systemd docker file
  raw: grep -q  "[Service]" "/etc/systemd/system/docker.service.d/http-proxy.conf" || echo '[Service]' >> /etc/systemd/system/docker.service.d/http-proxy.conf
  when: docker_proxy

- name: Adds HTTP_PROXY environment to systemd docker file
  raw: grep -q "Environment="{{ item }}={{ http_proxy_address }}"" "/etc/systemd/system/docker.service.d/http-proxy.conf"|| echo 'Environment="{{ item }}={{ http_proxy_address }}"' >> /etc/systemd/system/docker.service.d/http-proxy.conf
  with_items:
    - http_proxy
    - HTTP_PROXY
  when: not (http_proxy_address is undefined or http_proxy_address is none or http_proxy_address | trim == '') and docker_proxy

- name: Adds HTTPS_PROXY environment to systemd docker file
  raw: grep -q "Environment="{{ item }}={{ https_proxy_address }}"" "/etc/systemd/system/docker.service.d/http-proxy.conf"|| echo 'Environment="{{ item }}={{ https_proxy_address }}"' >> /etc/systemd/system/docker.service.d/http-proxy.conf
  with_items:
    - https_proxy
    - HTTPS_PROXY
  when: not (https_proxy_address is undefined or https_proxy_address is none or https_proxy_address | trim == '') and docker_proxy

- name: Adds NO_PROXY environment to systemd docker file
  raw: grep -q "Environment="{{ item }}={{ no_proxy_list }}"" "/etc/systemd/system/docker.service.d/http-proxy.conf"|| echo 'Environment="{{ item }}={{ no_proxy_list }}"' >> /etc/systemd/system/docker.service.d/http-proxy.conf
  with_items:
    - no_proxy
    - NO_PROXY
  when: not (no_proxy_list is undefined or no_proxy_list is none or no_proxy_list | trim == '') and docker_proxy

- name: Reload systemd
  raw: systemctl daemon-reload
  when: docker_proxy

- name: Touch /etc/apt/apt.conf.d/02-apt-proxy
  raw: touch /etc/apt/apt.conf.d/02-apt-proxy
  when: not (apt_http_proxy_address is undefined or apt_http_proxy_address is none or apt_http_proxy_address | trim == '') and (apt_http_proxy or apt_https_proxy or apt_ftp_proxy)

- name: set http proxy to /etc/apt/apt.conf.d/02-apt-proxy
  raw: echo 'Acquire::http::proxy "{{ apt_http_proxy_address }}";' >> /etc/apt/apt.conf.d/02-apt-proxy
  when: not (apt_http_proxy_address is undefined or apt_http_proxy_address is none or apt_http_proxy_address | trim == '') and apt_http_proxy

- name: set https proxy to /etc/apt/apt.conf.d/02-apt-proxy
  raw: echo 'Acquire::https::proxy "{{ apt_https_proxy_address }}";' >> /etc/apt/apt.conf.d/02-apt-proxy
  when: not (apt_https_proxy_address is undefined or apt_https_proxy_address is none or apt_https_proxy_address | trim == '') and apt_https_proxy

- name: set ftp proxy to /etc/apt/apt.conf.d/02-apt-proxy
  raw: echo 'Acquire::ftp::proxy "{{ apt_ftp_proxy_address }}";' >> /etc/apt/apt.conf.d/02-apt-proxy
  when: not (apt_ftp_proxy_address is undefined or apt_ftp_proxy_address is none or apt_ftp_proxy_address | trim == '') and apt_ftp_proxy
