---

#Installs new feature

- hosts: all
  become: yes
  tasks:
    - name: Force git pull - in case something was changed on secbot machine
      command: "{{ item }}"
      args:
        chdir: "{{ bots_dir }}"
      with_items: 
        - git fetch --all
        - git reset --hard origin/master

    - name: Make everything in plugins dir executable
      file:
        path: "{{ bots_dir}}/plugins"
        mode: a+x
        recurse: yes

    - name: Stop .py
      command: pkill python3
      ignore_errors: True

    - name: Start secbot.py in background
      shell: "(cd {{ bots_dir }}; python3 secbot.py &>>/var/log/secbot.log &)"
      async: 10


