---
#Installs new feature
- name: Install Pan-Net root CA
  hosts: all
  become: yes
  gather_facts: yes
  roles:
  - ansible-trust-ca
  tags:
    - root-ca-install

- hosts: all
  vars_files:
  - group_vars/clouds.yml
  - group_vars/all.yml
  become: yes
  tasks:
    - name: Force git pull - in case something was changed on secbot machine
      command: "{{ item }}"
      args:
        chdir: "{{ bots_dir }}"
      with_items: 
        - git fetch --all
        - git reset --hard origin/master

    - name: Make everything in plugins dir executable
      file:
        path: "{{ bots_dir}}/plugins"
        mode: a+x
        recurse: yes

    - name: Install python-keystoneclient
      command: "pip3 install python-keystoneclient"

    - name: Copy clouds_auth_data to vault
      copy:
        content: "{{ clouds_auth_data }}"
        dest: "/home/ubuntu/vault/clouds.json"
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Enable and restart service
      systemd:
        name: secbot
        state: restarted
