---

#Deploys secbot

#- hosts: all
#  become: yes
#  gather_facts: false
#  roles:
#    - { role: ansible-set-proxy, http_proxy_address: "{{ http_proxy }}", https_proxy_address: "{{ https_proxy }}", tags: ["set-proxy"] }


# this block is mainly because Ubuntu xenial doesn't have  
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - { role: ansible-py2-bootstrap, tags: [ "py2-bootstrap"] }

- hosts: all
  become: yes
  roles:
#    - { role: ansible-locale, when: ansible_os_family == 'Debian', tags: ['locale'] }
    - { role: ansible-fqdn, tags: ['fqdn'] }

- hosts: all
  become: yes
  tasks:
    - name: Copy .gitconfig for ubuntu user or other users
      template:
        src: .gitconfig
        dest: "/home/{{ item }}/.gitconfig"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0644
      with_items:
        - ubuntu

    - name: Copy .gitconfig for ubuntu user or other users
      template:
        src: .gitconfig
        dest: /root/.gitconfig
        owner: root
        group: root
        mode: 0644

    - name: Apt update
      apt:
        update_cache: yes

    - name: Install basic packages
      apt:
        name: "{{ item }}"
        allow_unauthenticated: yes
        state: present
      environment:
        http_proxy: "{{ http_proxy | default ('') }}"
        https_proxy: "{{ https_proxy | default ('') }}"
      with_items:
        - git
        - mc
        - python
        - python3
        - python-pip
        - python3-pip
        - libssl-dev
        - qrencode
        - jq
      tags: basicpkg

    - name: Remove repo dir
      file:
        state: absent
        path: "{{ bots_dir }}"

    - name: Create repo dir
      file:
        state: directory 
        path: "{{ bots_dir }}"
        owner: ubuntu
        group: ubuntu

    - name: Cloning bots repo
      git:
        repo: "{{ bots_repo }}"
        dest: "{{ bots_dir }}"
        update: yes
        force: yes
      environment:
        http_proxy: "{{ http_proxy | default ('') }}"
        https_proxy: "{{ https_proxy | default ('') }}"

    - name: Make everything in /plugins dir executable
      file:
        path: "{{ bots_dir }}/plugins"
        mode: a+x
        recurse: yes

    - name: Add secbot public key to the target - user
      lineinfile:
        path: /home/ubuntu/.ssh/authorized_keys
        line: "{{ item }}"
      with_items:
        - "{{ secbot_pubkey }}"

    - name: Add secbot public key to the target - root
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{ item }}"
      with_items:
        - "{{ secbot_pubkey }}"


    - name: Install packages for bot functions
      command: "{{ item }}"
      with_items:
        - pip3 install slackclient
        - pip3 install authenticator
        - pip3 install pyotp
        - pip3 install shodan
 
    - name: Install packages for bot functions
      apt:
        name: "{{ item }}"
      with_items:
        - python3-openstackclient
        - python3-neutronclient
        - python3-novaclient
        - python3-heatclient

    - name: Create vault dir
      file:
        state: directory 
        path: "/home/ubuntu/vault"
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: Copy secrets to vault (only if not present already)
      copy:
        src: bots.py
        dest: "/home/ubuntu/vault/bots.py"
        owner: ubuntu
        group: ubuntu
        mode: 0600
        force: no

    - name: Copy check script
      template:
        src: check_restart.sh
        dest: "/opt/check_restart.sh"
        owner: ubuntu
        group: ubuntu
        mode: 0777

    - name: Stop residual .py if running
      command: pkill python3
      ignore_errors: True

    - name: Touch log file
      file:
        path: "/var/log/{{ item }}"
        state: touch
        owner: syslog
        group: adm
        mode: 666
      with_items:
        - secbot.log

    - name: Add crontab job to restart secbot regularly in /etc/cron.d/secbot
      cron: minute="*" name="secbot"
        cron_file="secbot"
        user="root"
        job="/opt/check_restart.sh"
      tags: cronjob

    - name: Comment
      debug: msg="Update vault/bots.py with SLACKTOKEN and secrets needed for bot commands"





