---

#http_proxy: "http://proxy.hu.in.pan-net.eu:3128"
#https_proxy: "http://proxy.hu.in.pan-net.eu:3128"

git_user: "xxx"
git_email: "juraj@abc.eu"

bots_dir: "/data/secbot"
bots_repo: "https://gitlab.abc.eu/secbot.git"


secbot_pubkey: "ssh-rsa abc secbot"


